// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqizLh31p69HEWLt4Mx6PjGHc4m4SgaV4',
    appId: '1:973525613629:web:c630b80a4a56d2a51cbe54',
    messagingSenderId: '973525613629',
    projectId: 'pokedex-mobile-2c33a',
    authDomain: 'pokedex-mobile-2c33a.firebaseapp.com',
    storageBucket: 'pokedex-mobile-2c33a.appspot.com',
    measurementId: 'G-YDVQY49MCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDVFlbvl4BKS9eBpil1LtfZxPj6k1KmU',
    appId: '1:973525613629:android:fc444787d05a8d251cbe54',
    messagingSenderId: '973525613629',
    projectId: 'pokedex-mobile-2c33a',
    storageBucket: 'pokedex-mobile-2c33a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6aGJePGwUojDHnSmUb7q68vHGHzaM7rc',
    appId: '1:973525613629:ios:3e1312587bc0c2041cbe54',
    messagingSenderId: '973525613629',
    projectId: 'pokedex-mobile-2c33a',
    storageBucket: 'pokedex-mobile-2c33a.appspot.com',
    iosClientId: '973525613629-ihb8jqddf4us7coua1o0tsq0no19inpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6aGJePGwUojDHnSmUb7q68vHGHzaM7rc',
    appId: '1:973525613629:ios:287cf8d755c449471cbe54',
    messagingSenderId: '973525613629',
    projectId: 'pokedex-mobile-2c33a',
    storageBucket: 'pokedex-mobile-2c33a.appspot.com',
    iosClientId: '973525613629-5k6o0fbohefhgo47lb1sfp3j5qmniroo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
